baseURL: https://open94006.github.io/
languageCode: zh-tw
title: Daniel Lin 林致嘉
# theme: ['PaperMod']
ignoreLogs: ['warning-goldmark-raw-html']
markup:
    goldmark:
        renderer:
            unsafe: true
            hardWraps: true
    highlight:
        noClasses: false
menus:
    main:
        - name: 關於我
          pageRef: /about
          weight: 10
        - name: 文章分類
          pageRef: /categories
          weight: 20
        - name: 標籤
          pageRef: /tags
          weight: 30
        - name: 歷史紀錄
          pageRef: /archives
          weight: 40
        - name: 搜尋
          pageRef: /search
          weight: 50
outputs:
    home:
        - HTML
        - RSS
        - JSON # necessary for search
params:
    assets:
        favicon: '/favicon.ico'
        favicon16x16: '/favicon-16x16.png'
        favicon32x32: '/favicon-32x32.png'
        apple_touch_icon: '/apple-touch-icon.png'
        showCodeCopyButtons: true
    homeInfoParams:
        Title: Daniel Lin 林致嘉
        imageUrl: '/headshot.jpg'
        Content: |
            這裡是我生活與工作紀錄的地方  
            把這顆種子埋下，希望能長大茁壯😎
    socialIcons: # optional
        - name: 'github'
          url: 'https://github.com/open94006'
    defaultTheme: auto
    searchHidden: true
    ShowPostNavLinks: true
    ShowToc: true
    TocOpen: true # Optional: opens TOC by default
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ['title', 'permalink', 'summary', 'content']
    taxonomies:
        categories: categories
        tag: tags
module:
    imports:
        - path: ./PaperMod
        # - path: github.com/adityatelange/hugo-PaperMod
